prestodb/prestodb.github.io

resources.html

Use EMR Instead of Elastic MapReduce, which is a legacy name which is not used anymore

Correct the AWS product names

---

website/static/index.html

Remove quick links on landing page, link to Slack instead of IRC

---

website/blog/2019-09-26-tablescan-structs.md

Had an extra ` and it was messing up some formatting.

Fix typo in tablescan structs blog post

---

website/siteConfig.js
website/static/community.html
website/static/download.html
website/static/faq.html
website/static/index.html
website/static/overview.html
website/static/resources.html

The header docs link was not resolving, and in various places the GitHub repos
still pointed to github.com/facebook/presto.  These have been updated to point
to the current locations.

Update links to docs and GitHub

---

website/siteConfig.js

Tested it with 'yarn build' and the resulting site has the right value in a CNAME file.

Add cname to siteConfig.js

---

website/static/community.html
website/static/download.html
website/static/faq.html
website/static/img/github.svg
website/static/index.html
website/static/join.html
website/static/overview.html
website/static/resources.html

This commit adds a Presto Foundation page, with descriptions of membership
benefits and links to become a member.
It also includes the octocat logo, as there is no longer room in the header for
the word "GitHub". This commit includes changes to the menus for all existing
static pages, and the blog.

Add a join page and change GitHub to octocat logo

---

website/static/CONTRIBUTING.md

Update the CONTRIBUTING.md file to remove reference to the Facebook CLA, and instead describe the EasyCLA process.

Update cla info

---

website/static/community.html
website/static/download.html
website/static/faq.html
website/static/index.html
website/static/join.html
website/static/overview.html
website/static/resources.html

Fix the spacing in the header.  Adding the "Foundation" menu item caused the top
menu bar to overflow.  Changing "Overview" to "About" provided sufficient space
so that the top bar no longer overflows.

Change Overview to About (spacing fix)

---

website/core/Footer.js
website/siteConfig.js
website/static/community.html
website/static/css/footer.css
website/static/download.html
website/static/faq.html
website/static/index.html
website/static/join.html
website/static/overview.html
website/static/resources.html
website/static/static/presto.css

This update replaces the old footer text with standard LF text.  Because the LF
text is longer and includes links, it required some changes to CSS and
(apparently?) a workaround in Docusaurus.

Update footer to standard LF text

---

website/static/getting-started.html

Per discussion in the Outreach Committee Meeting dating July 1st, it was agreed that third party content from vendors will be added to the Resources page on the website. Core documentation should not have references to vendor content. 
Once the official dockerhub for prestodb is ready, this tutorial will be moved to the Resources page.

Update getting started to remove 3rd party ref.

---

website/blog/2020-08-04-prestodb-and-hudi.md

MINOR change - Refer to as `Apache Hudi` instead of `Hudi`

Fix title of 'PrestoDB and Hudi' blog

---

website/static/join.html
website/static/static/landscape.css

This PR embeds a landscape directly on the foundation page, replacing the static list of companies and logos, which had gotten out of date.

Improve landscape embed

---

website/static/static/landscape.css

Removed the "h1" css block that's removing the blog title. Tested on laptop. Fixes https://github.com/prestodb/presto/issues/16176

Fix display of the missing blog title

---

website/static/resources.html

Hey folks 👋 Not sure about this but maybe it makes sense to have a link to this [long tutorial](https://cube.dev/blog/ahana-integration-querying-multiple-data-sources-with-managed-presto-and-cube) by @mikulskibartosz somewhere on the Presto website? WDYT?
I added it under *Resources* since there's already a *Tutorials* subsection there:

Add Presto + Cube tutorial

---

website/static/docs/0.280/admin/resource-groups.html

Resource group name only allows alphabets and numbrers but the documentation example shows special characaters (i.e. tool_name) allowed. This lead to issues when users trying to use it. As part of this PR correcting that and providing info around the restrictions with the resource group name.

Updating resource group documentation with allowed name template

---

website/static/events/community-office-hours.html
website/static/events/index.html
website/static/index.html

Also fix links on events/community-office-hours page, and add redirect for /events
Preview at: https://prestodb.fosforus.com/

Update home banner

---

website/static/what-is-presto.html

Found a few NIT typos as I was reading through [this page](https://prestodb.io/what-is-presto.html) 🙂

Fix minor typos on 'What is Presto' static page

---

.github/workflows/publish.yml

The workflow automatically releases website to GitHub Pages by running `yarn run publish-gh-pages` command.
~The workflow should be deleted, because GitHub Pages is not used anymore to host the website,~
Job `gh-release` in publish workflow should be deleted, because GitHub Pages is not used anymore to host the website.

Remove gh-release job in publish workflow

---

.github/workflows/publish.yml

This reverts commit 74b16e09a224095d1e20110db5aa8f9be322b50f.
We will need to host docs on github again, because wordpress hosting storage quota issue.
@alileclerc has more details.

Revert "Remove gh-release job in publish workflow"

---

website/blog/2023-08-02-presto-on-kubernetes-with-helm-prestocon-day.md

helm and kubectl commands were wrong and will cause issues for anyone trying to setup presto on local by following this blog. Fixed the commands.

Fix helm and kubectl commands
