index.html
This should hopefully cut down on bogus messages.
=> Remove group email address from website

resources.html
@martint @electrum Can you take a look at this pull request when you get a chance?
=> Add yanagishima to the list of GUI presto tool

resources.html
@electrum please pull this in.
=> Fix typo and update on Resources page.

faq.html, resources.html
Added a section on Presto on AWS/Azure.
Corrected some links and names related to the new Starburst website.
=> Presto on AWS/Azure + naming update

presto-docs.sh, website/static/download.html, website/static/index.html, website/static/static/js/version.js, website/static/static/presto.css
=> Add link to download page on landing page

presto-docs.sh, website/static/download.html, website/static/index.html, website/static/static/js/version.js, website/static/static/presto.css
=> Add release statistics to download and landing page

website/blog/2019-07-19-memory-tracking.md
This is how it looks like: [Memory Management in Presto.pdf](https://github.com/prestodb/prestodb.github.io/files/3452361/Memory.Management.in.Presto.pdf)
=> Add memory management blog post

website/blog/2019-12-16-growing-the-presto-foundation.md
https://prestodb.io/join.html
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Add Presto Foundation 2020 blog

website/blog/2019-12-16-growing-the-presto-foundation.md
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Fix author id for Brian

website/static/community.html
@brianwarner @galemccommons @dborkar
Before
After
=> Adding Quicklinks to community page

website/static/getting-started.html, website/static/index.html, website/static/static/basic.css, website/static/static/presto.css
Fixed mobile UX issues - Join Meetup button on homepage and Foundation graphic on /join
Added a new Getting Started page that will link from the home page button "Get Started"
=> new getting started page and mobile ux fix

website/static/community.html, website/static/download.html, website/static/faq.html, website/static/getting-started.html, website/static/index.html, website/static/join.html, website/static/overview.html, website/static/resources.html
Per discussion with @dborkar, adding some analytics to the website.
=> Add analytics

website/static/community.html
@adamjshook @dborkar 
minor layout changes
=> change main comms channel to slack, move TSC down

website/static/join.html
=> Update membership form links

website/static/community.html, website/static/resources.html
@aweisberg @dborkar 
Added new sections to the Resources page for community content so community users can add their content here, and broke out the page into 3 sections for more organization.
Added "Are you a Presto user" section to Community page, and also added Github discussions to quicklinks. Fixed bolded font at bottom issue.
=> Updating Resources page & minor edits to Community page

website/blog/2020-07-17-alluxio-hybrid-cloud.md
Fix broken image links after the blog date was updated.
=> [Blog] Fix date for images in Hybrid cloud blog

website/static/index.html, website/static/static/presto.css
Adjustments to index.html and static presto.css to add prestocon banner
=> 2020 prestocon banner

website/static/index.html
=> Add Alibaba to Banner

website/core/Footer.js, website/static/community.html, website/static/download.html, website/static/faq.html, website/static/getting-started.html, website/static/index.html, website/static/join.html, website/static/overview.html, website/static/prestocon.html, website/static/resources.html
=> Updates to footer links

website/blog/2020-08-06-presto-in-ea.md
change thousands of games to dozens of games each year.
=> minor phrase changes

website/siteConfig.js
tested on my laptop by looking at local file from the website/build directory, e.g., prestodb.github.io/website/build/prestodb.github.io/docs/0.247/security/cli.html
=> Update website config with all css files for new docs theme

website/static/join.html
Move from Docusign Powerforms to the LF's autojoin platform.
=> Update membership form

LICENSE
The license text on this is out of sync with the project license.
@aweisberg and @fbwut, can you please review and merge?
=> Add Apache license text

website/siteConfig.js, website/static/prestoconday2021.html
two CSS files needed to be added to the siteconfig file so they are included in the yarn build for static assets. Also removed a console.log command from prestonconday2021.html
=> add css files for prestoconday to site config

website/blog/2021-06-14-Commitment-to-Presto-Open-Source-Community.md
=> 2021 blog 1 update

website/static/join.html
=> Update membership levels to include 2021 revisions

website/static/join.html
=> Add service desk links to Foundation page.

website/static/CONTRIBUTING.md
=> Add Ali to maintainers

website/blog/2022-05-10-faster-presto-queries-with-parquet-page-index.md
Adding truncate tag for 2022-05-10-faster-presto-queries-with-parquet-page-index blog
CC @alileclerc
=> Adding truncate tag

website/blog/2019-12-23-improve-presto-planner.md
As I've mentioned in [Slack](https://prestodb.slack.com/archives/C07JH9WMQ/p1675578461867929), the image in this post can be fixed by modifying the URL directly.
=> Fix image url in doc.

website/static/community.html, website/static/data/Videos_PrestoCon2022.js, website/static/index.html, website/static/videos.html
Each page load checks github for the latest star count.
Preview at:
https://prestodb.fosforus.com/
https://prestodb.fosforus.com/community.html
=> adds automatic github star count to home and community

website/static/index.html, website/static/videos.html
Preview home banner and videos page at: https://prestodb.fosforus.com/
=> updated home and videos for prestocon 2022

website/static/foundation/overview.html, website/static/join.html
Also includes a fix for nav bar on join page. Test at https://prestodb.fosforus.com/foundation
=> Redirect for foundation

website/static/css/custom.css, website/static/data/GetStarted_Cards.js, website/static/getting-started.html, website/static/index.html
Removed prestocon day banner from home, and removed one card on getting started.
Preview at:
https://prestodb.fosforus.com/
https://prestodb.fosforus.com/getting-started.html
=> Post-prestoconday updates

website/siteConfig.js, website/static/community.html, website/static/getting-started.html, website/static/index.html, website/static/join.html, website/static/powered-by-presto.html, website/static/tutorials.html, website/static/videos.html, website/static/what-is-presto.html
Preview on static pages and blog at https://prestodb.fosforus.com/
The Hubspot proactive newsletter popup will appear after a few seconds.
=> Added Hubspot script to head

website/blog/2023-06-23-prestocon-day-recap.md
=> Prestoconday blog 2

website/static/community.html, website/static/events/community-office-hours.html
Preview at:
https://prestodb.fosforus.com/community.html
https://prestodb.fosforus.com/events/community-office-hours.html
=> Added office hours page and link from community page

website/static/community.html, website/static/events/community-office-hours.html, website/static/getting-started.html, website/static/index.html, website/static/join.html, website/static/news.html, website/static/newsletter.html, website/static/powered-by-presto.html, website/static/tutorials.html, website/static/videos.html, website/static/what-is-presto.html
Preview at: https://prestodb.fosforus.com/
=> remove office hours banner from home, update copyright

website/blog/2023-08-29-presto-working-groups.md
=> Add blog 2023-08-29-presto-working-groups.md

.github/workflows/publish.yml
docusaurus's dependencies need newer node version.
=> update node version for GHA
